# Etapa 1: Construcción
FROM node:18 AS build
WORKDIR /app

  # Copiar package.json e instalar dependencias
COPY package*.json ./
RUN npm install

  # Copiar el resto del código y compilar
COPY . .
RUN npm run build -- --configuration production

  # Etapa 2: Servir con Nginx
FROM nginx:1.25-alpine
  # Copiar el build de Angular al directorio de Nginx
COPY --from=build /app/dist /usr/share/nginx/html

  # Copiar configuración personalizada de Nginx (opcional)
  # COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
